# Use postgres/example user/password credentials
version: "3.5"

services:

    i2b2app:
       build: ./i2b2app
       restart: on-failure
       # ports:
       #    - 8080:8080
       environment:
         SECRETS: /run/secrets/secrets
       secrets:
         - secrets

    i2b2db:
        build: ./i2b2db
        restart: on-failure
        # links:
        #    - i2b2app
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets

    shrinedb:
        build: ./shrinedb
        restart: on-failure
        # links:
        #    - shrine
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets

    shrine:
        build: ./shrine
        restart: on-failure
        ports:
           - 7443:6443
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets
        volumes:
           - ./shrine/cert/shrine:/opt/cert

    hub:
       build:
         context: ./shrine
         dockerfile: Hub
       restart: on-failure
       ports:
          - 6443:6443
     #    - 8080:8080
       environment:
         SECRETS: /run/secrets/secrets
       secrets:
         - secrets
       volumes:
          - ./shrine/cert/hub:/opt/cert

    webserver:
        build: ./webserver
        restart: on-failure
        ports:
           - 80:80
        # links:
        #    - i2b2app
        # volumes:
        #    - ./webserver/webclient:/var/www/html/
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets
    #
    #
    # pgadmin:
    #     image: thajeztah/pgadmin4
    #     restart: on-failure
    #     ports:
    #        - 5050:5050
    omnidb:
      image: sorrell/alpine-omnidb
      restart: on-failure
      ports:
        - 5050:9000

secrets:
  secrets:
    file: secrets.txt
