# Use postgres/example user/password credentials
version: "3.5"

services:

    i2b2app:
       build: ./i2b2app
       restart: "no"
       # ports:
       #    - 8080:8080
       environment:
         SECRETS: /run/secrets/secrets
       secrets:
         - secrets

    i2b2db:
        build: ./i2b2db
        restart: "no"
        # links:
        #    - i2b2app
        environment:
          SECRETS: /run/secrets/secrets
        ports:
           - 5432:5432
        secrets:
          - secrets

    shrinedb:
        build: ./shrinedb
        restart: "no"
        # links:
        #    - shrine
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets

    shrine:
        build: ./shrine
        restart: "no"
        ports:
           - 7443:6443
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets
        volumes:
           - ./shrine/cert/shrine:/opt/cert

    hub:
      build:
        context: ./shrine
        dockerfile: Hub
      restart: "no"
      ports:
           - 6443:6443
           # - 8080:8080
      environment:
        SECRETS: /run/secrets/secrets
      secrets:
        - secrets
      volumes:
        - ./shrine/cert/hub:/opt/cert

    webserver:
        build: ./webserver
        restart: "no"
        ports:
           - 80:80
        # links:
        #    - i2b2app
        # volumes:
        #    - ./webserver/webclient:/var/www/html/
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets
    #
    #
    pgadmin:
        image: thajeztah/pgadmin4
        restart: "no"
        restart: on-failure
        ports:
           - 5050:5050
    # omnidb:
    #   image: sorrell/alpine-omnidb
    #   restart: "no"
    #   ports:
    #     - 5050:9000

secrets:
  secrets:
    file: secrets.txt
